### ISSUE TITLE
Does this work with iPad?

### ISSUE THREAD

**Issue by ctbritt** [AngryBeaver/beavers-mobile#1]
Hi, this doesn't seem to do anything on an ipad. Does it support iPadOS?

**Comment by AngryBeaver** [comment]
It does successfully run on my ipad... :-) as helpfull as this information is to you :-/.

It should however not have anything todo with ios but with the browser running your foundry.
I have tested it with chrome, and silk (firet-tablet), also safari on ipad does work for me but:

https://foundryvtt.com/article/requirements/
silk, safari are not officially supported by foundry.


Also you should enable module: TouchVTT.
Else then that look into my troubleshooting section maybe i covered your problem there.
https://github.com/AngryBeaver/beavers-mobile/blob/main/README.md#troubleshooting

**Comment by ctbritt** [comment]
so, thanks for mentioning TouchVTT, I didn't know that needed to be enabled. But this is what I see on my ipad running chrome: 
<img width="1366" alt="httpsfoundry azthir-terra comgame png" src="https://user-images.githubusercontent.com/4516034/200009313-7221590e-edf2-4c88-a817-4daec027107d.png">

**Comment by AngryBeaver** [comment]
Well, sry don't know. 


My module does not enable using mobile. It just enhance playing with it. TouchVTT is i think a must if you want to play with mobiles.

My Module just adds targeting and moving without canvas and also comes with a slim version of charsheet. Beside that my troubleshooting might help with probelms i encountered using some devices but i wont be the guy that fixes all mobile problems :-).

but here is what i would do:
1.) try diffrent browser anything that is officially supported.
2.) disable all modules except TouchVTT
3.) hit f12 and look into the debug logs and search for error messages.

However bad this looks you might also do not need more. This is obviously the combatencounter tab that you see. you might be able to open the char sheet from here by tabbing the hero icon twice. That way you have a charsheet and the combat encounter wich is mostly enough
